source "https://rubygems.org"
git_source(:github) { |name| "https://github.com/#{name}.git" }

gem "rails", "= 6.0.3.2"
gem "will_paginate"

gem "carrierwave_direct",  github: "feedbin/carrierwave_direct",  ref: "a0bc323"
gem "dalli",               github: "feedbin/dalli",               branch: "feedbin"
gem "feedjira",            github: "feedbin/feedjira",            ref: "e6b7b11"
gem "feedkit",             github: "feedbin/feedkit",             branch: "master"
gem "grocer-pushpackager", github: "feedbin/grocer-pushpackager", ref: "6b01b4e", require: "grocer/pushpackager"
gem "html-pipeline",       github: "feedbin/html-pipeline",       ref: "1e77ecf"
gem "html_diff",           github: "feedbin/html_diff",           ref: "013e1bb"
gem "opml_saw",            github: "feedbin/opml_saw",            ref: "61d8c2d"
gem "elasticsearch-model", github: "feedbin/elasticsearch-rails", branch: "2.x"

gem "activerecord-import"
gem "addressable", require: "addressable/uri"
gem "apnotic"
gem "autoprefixer-rails"
gem "bcrypt"
gem "bcrypt-ruby"
gem "bootsnap", require: false
gem "carrierwave"
gem "clockwork"
gem "coffee-rails"
gem "connection_pool"
gem "curb"
gem "dotenv-rails"
gem "elasticsearch", "~> 2.0"
gem "evernote_oauth"
gem "fog-aws"
gem "foreman"
gem "honeybadger"
gem "htmlentities"
gem "http"
gem "httparty"
gem "jbuilder"
gem "jquery-rails"
gem "librato-rails", "~> 1.4.2"
gem "lograge"
gem "mini_racer"
gem "net-http-persistent"
gem "oauth"
gem "pg"
gem "premailer-rails"
gem "rack-attack"
gem "rails-controller-testing"
gem "raindrops"
gem "redcarpet"
gem "redis"
gem "responders"
gem "reverse_markdown"
gem "rmagick", require: false
gem "rubyzip"
gem "sanitize"
gem "sass-rails"
gem "sidekiq"
gem "stripe", "~> 4.24.0"
gem "stripe_event"
gem "twitter"
gem "twitter-text"
gem "uglifier"
gem "unicode-emoji"
gem "unicorn"

group :development do
  gem "benchmark-ips"
  gem "better_errors"
  gem "binding_of_caller"
  gem "capistrano"
  gem "capistrano-bundler"
  gem "capistrano-rails"
  gem "htmlbeautifier"
  gem "listen"
  gem "silencer"
  gem "spring"
end

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "capybara"
  gem "coveralls", require: false
  gem "faker"
  gem "minitest"
  gem "minitest-stub-const"
  gem "minitest-stub_any_instance"
  gem "puma"
  gem "selenium-webdriver"
  gem "standard"
  gem "stripe-ruby-mock", "= 2.5.0", require: "stripe_mock"
  gem "webmock", "= 3.8.0"
end

gem "pg"
gem "unicorn"

gem "feedjira", github: "feedbin/feedjira", ref: "e6b7b11"
gem "feedkit", github: "feedbin/feedkit", branch: "master"

gem "opml_saw", github: "feedbin/opml_saw", ref: "61d8c2d"
gem "html-pipeline", github: "feedbin/html-pipeline", ref: "20162f9"
gem "grocer-pushpackager", github: "feedbin/grocer-pushpackager", ref: "6b01b4e", require: "grocer/pushpackager"
gem "html_diff", github: "feedbin/html_diff", ref: "c7c15ce"
gem "carrierwave_direct", github: "feedbin/carrierwave_direct", ref: "a0bc323"
gem "dalli", github: "feedbin/dalli", branch: "feedbin"

gem "sass-rails"
gem "mini_racer"
gem "coffee-rails"
gem "uglifier", "= 4.1.11"
gem "autoprefixer-rails"
gem "rubyzip"

gem "apnotic"
gem "json"
gem "activerecord-import", ">= 0.4.1"
gem "redis"
gem "jquery-rails"
gem "will_paginate"
gem "sanitize"
gem "carrierwave"
gem "fog-aws"
gem "clockwork"
gem "jbuilder"
gem "bcrypt-ruby"
gem "honeybadger"
gem "addressable", require: "addressable/uri"
gem "librato-rails", "= 1.4.2"
gem "foreman", "= 0.63.0"
gem "readability_parser"
gem "lograge"
gem "connection_pool"
gem "httparty"
gem "oauth"
gem "evernote_oauth"
gem "rmagick", require: false
gem "reverse_markdown"
gem "htmlentities"
gem "dotenv-rails"
gem "redcarpet"
gem "premailer-rails"
gem "http"
gem "net-http-persistent"
gem "elasticsearch", "~> 7.0"
gem "elasticsearch-model", "~> 7.0"
gem "sidekiq"
gem "raindrops"
gem "curb"
gem "twitter"
gem "twitter-text"
gem "bootsnap", require: false
gem "unicode-emoji"
gem "rack-attack"
gem "jbuilder_cache_multi"
gem "bcrypt"

# Stripe
gem "stripe", "~> 4.24.0"
gem "stripe_event"
